CREATE TABLE XXCCMS_APP_AMEND_TYPES_V (
          APP_TYPE_CODE          VARCHAR2(255 CHAR) PRIMARY KEY,
          APP_TYPE_DESCRIPTION   VARCHAR2(255 CHAR),
          COST_LIMIT_CAP         VARCHAR2(255 CHAR),
          DEVOLVED_POWERS_IND    VARCHAR2(255 CHAR),
          DEFAULT_LAR_SCOPE_FLAG VARCHAR2(255 CHAR)
);