Insert into XXCCMS_PUI_OPA_ENTITIES_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, REV_RELATIONSHIP_TEXT, INSTANCE_NAME_COLUMN, PRIMARY_KEY, ENTITY_LEVEL, PARENT_ENTITY_CODE, ENTITY_DISPLAY_SEQUENCE)
Values
    ('parent', 'PARENTAL TEST DATA', '-', 'SOME RANDOM PARENTAL DATA', 'PARENTAL_ID', '0', 'PARENT', '000005');

Insert Into XXCCMS_PUI_OPA_ATTRIBUTE_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, OPA_ATTRIBUTE_NAME, OPA_ATTRIBUTE_DISPLAY_NAME, DISPLAY_SEQUENCE, SUMMARY_DISPLAY_FLAG, ENTITY_DISPLAY_SEQUENCE)
Values
    ('parent', 'PARENTAL TEST DATA', 'P_DATA_TYPE', 'Parent data type', '000001',  'Y', '000005');

Insert into XXCCMS_PUI_OPA_ENTITIES_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, REV_RELATIONSHIP_TEXT, INSTANCE_NAME_COLUMN, PRIMARY_KEY, ENTITY_LEVEL, PARENT_ENTITY_CODE, ENTITY_DISPLAY_SEQUENCE)
Values
    ('childOne', 'CHILD ONE TEST DATA', '-', 'SOME RANDOM CHILD ONE DATA', 'CHILD_ONE_ID', '2', 'CHILD_ONE', '000010');

Insert Into XXCCMS_PUI_OPA_ATTRIBUTE_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, OPA_ATTRIBUTE_NAME, OPA_ATTRIBUTE_DISPLAY_NAME, DISPLAY_SEQUENCE, SUMMARY_DISPLAY_FLAG, ENTITY_DISPLAY_SEQUENCE)
Values
    ('childOne', 'CHILD ONE TEST DATA', 'C1_DATA_TYPE', 'Child one data type', '000001',  'Y', '000010');

Insert into XXCCMS_PUI_OPA_ENTITIES_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, REV_RELATIONSHIP_TEXT, INSTANCE_NAME_COLUMN, PRIMARY_KEY, ENTITY_LEVEL, PARENT_ENTITY_CODE, ENTITY_DISPLAY_SEQUENCE)
Values
    ('childTwo', 'CHILD TWO TEST DATA', '-', 'SOME RANDOM CHILD TWO DATA', 'CHILD_ONE_ID', '2', 'CHILD_ONE', '000015');

Insert Into XXCCMS_PUI_OPA_ATTRIBUTE_V
(OPA_ENTITY_NAME, OPA_ENTITY_DISPLAY_NAME, OPA_ATTRIBUTE_NAME, OPA_ATTRIBUTE_DISPLAY_NAME, DISPLAY_SEQUENCE, SUMMARY_DISPLAY_FLAG, ENTITY_DISPLAY_SEQUENCE)
Values
    ('childTwo', 'CHILD TWO TEST DATA', 'C2_DATA_TYPE', 'Child two data type', '000001',  'Y', '000015');




