DROP TABLE XXCCMS_COMMON_LOV_V;
DROP TABLE XXCCMS_APP_AMEND_TYPES_V;
DROP TABLE XXCCMS_APP_CASE_STATUS_V;
DROP TABLE XXCCMS_COUNTRY_V;
DROP TABLE XXCCMS_OUTCOME_RESULTS_V;
DROP TABLE XXCCMS_STAGE_END_V;
DROP TABLE XXCCMS_PER_RELTOCASE_V;
DROP TABLE XXCCMS_ORG_RELTOCASE_V;
DROP TABLE XXCCMS_AWARD_TYPE_V;
DROP TABLE XXCCMS_CATEGORY_OF_LAW_V;
DROP TABLE XXCCMS_EVIDENCE_DOC_TYPE_V;
DROP TABLE XXCCMS_PUI_OPA_ENTITIES_V;
DROP TABLE XXCCMS_PUI_OPA_ATTRIBUTE_V;
DROP TABLE XXCCMS_PROVIDER_REQTYPES_V;



