CREATE TABLE XXCCMS_PROCEEDING_V (
    PROCEEDING_CODE	VARCHAR2(30) PRIMARY KEY,
    PROCEEDING_NAME	VARCHAR2(80),
    DESCRIPTION	VARCHAR2(542),
    CATEGORY_OF_LAW_CODE	VARCHAR2(150),
    STAGE_END_LOV	VARCHAR2(150),
    OUTCOME_RESULT_LOV	VARCHAR2(150),
    MATTER_TYPE	VARCHAR2(30),
    AMENDMENT_ONLY	VARCHAR2(150),
    ENABLED_FLAG	VARCHAR2(1),
    ORDER_TYPE_REQUIRED	VARCHAR2(150),
    PROC_LAR_SCOPE	VARCHAR2(150)
);
