DROP TABLE XXCCMS.XXCCMS_PROVIDERCONTACTS_V;
DROP TABLE XXCCMS.XXCCMS_FEE_EARNER_OFFICES_V;
DROP TABLE XXCCMS.XXCCMS_FEE_EARNERS_V;
DROP TABLE XXCCMS.XXCCMS_PROVIDER_OFFICES_V;
DROP TABLE XXCCMS.XXCCMS_PROVIDERFIRMS_V;
