CREATE TABLE XXCCMS_SCOPELIMITATIONS_V (
    SCOPELIMITATIONS	VARCHAR2(30),
    DESCRIPTION	VARCHAR2(80),
    CATEGORY_OF_LAW_CODE	VARCHAR2(40),
    MATTER_TYPE	VARCHAR2(40),
    PROCEEDING_CODE	VARCHAR2(40),
    LEVEL_OF_SERVICE_CODE	VARCHAR2(40),
    STAGE	VARCHAR2(40),
    SCOPE_DEFAULT	VARCHAR2(150),
    DEFAULT_CODE	VARCHAR2(150),
    COST_LIMITATION	NUMBER,
    EMERGENCY	VARCHAR2(150),
    EMERGENCY_SCOPE_DEFAULT	VARCHAR2(150),
    NON_STD_WORDING_REQD	VARCHAR2(150),
    DEFAULT_WORDING	VARCHAR2(542),
    EMERGENCY_COST_LIMITATION	VARCHAR2(150)
);
