spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:CCMSPUI
    driver-class-name: oracle.jdbc.OracleDriver
    username: XXCCMS_PUI
    password: XXCCMS_PUI
    hikari:
      maximum-pool-size: 20 # Default is 10

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8009

laa:
  ccms:
    springboot.starter.auth:
      authentication-header: "Authorization"
      authorized-clients: '[
          {
              "name": "caab-ui",
              "roles": [
                  "ALL"
              ],
              "token": "d594f93f-e767-4b88-a9e9-2913441edfba"
          }
      ]'
      authorized-roles: '[
          {
              "name": "ALL",
              "URIs": [
                  "/**"
              ]
          }
      ]'
      unprotected-uris: [ "/actuator/**", "/swagger-ui.html", "/swagger-ui/**", "/v3/api-docs/**", "/favicon.ico",
                          "/open-api-specification.yml" ]
    metrics:
      health-exposed: true
      info-exposed: true
      metrics-exposed: true
      prometheus-exposed: true
      mappings-exposed: true
      env-exposed: true

