apiVersion: v1
kind: Service
metadata:
  name: laa-ccms-civil-caab-ebs-api-service
  namespace: laa-ccms-civil
  labels:
    app.kubernetes.io/name: caab-ebs-api
spec:
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8009
  selector:
    app.kubernetes.io/name: caab-ebs-api

