openapi: '3.0.0'
info:
  title: 'laa-ccms-data-api'
  version: '1.0.0'
paths:
  /users/{login-id}:
    get:
      tags:
        - users
      summary: 'Get User'
      operationId: 'getUser'
      parameters:
        - name: 'login-id'
          in: 'path'
          required: true
          schema:
            type: 'string'
            example: 'abc123'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userDetail"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
  /fee-earners:
    get:
      tags:
        - fee earners
      summary: 'Get Fee Earners'
      operationId: 'getFeeEarners'
      x-spring-paginated: true
      parameters:
        - name: 'provider-id'
          in: 'query'
          required: true
          schema:
            type: integer
            example: 12345
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/feeEarnerDetail"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
  /common-lookup-values:
    get:
      tags:
        - common lookup values
      summary: 'Get a list of common lookup values'
      operationId: 'getCommonLookupValues'
      x-spring-paginated: true
      parameters:
        - name: 'type'
          in: 'query'
          schema:
            type: 'string'
            example: 'CONTACT_TITLE'
        - name: 'code'
          in: 'query'
          schema:
            type: 'string'
            example: 'D'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/commonLookupDetail"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
components:
  schemas:
    officeDetail:
      type: 'object'
      properties:
        id:
          type: 'integer'
        name:
          type: 'string'
    providerDetail:
      type: 'object'
      properties:
        id:
          type: 'integer'
        name:
          type: 'string'
        offices:
          type: 'array'
          items:
            $ref: "#/components/schemas/officeDetail"
    userDetail:
      type: 'object'
      properties:
        user_id:
          type: 'integer'
        login_id:
          type: 'string'
        username:
          type: 'string'
        user_type:
          type: 'string'
        provider:
          $ref: "#/components/schemas/providerDetail"
        firms:
          type: 'array'
          items:
            $ref: "#/components/schemas/providerDetail"
        functions:
          type: 'array'
          items:
            type: 'string'
    feeEarnerDetail:
      allOf:
        - $ref: "#/components/schemas/page"
      type: 'object'
      properties:
        content:
          type: 'array'
          items:
            $ref: '#/components/schemas/contactDetail'
    contactDetail:
      type: 'object'
      properties:
        id:
          type: 'integer'
          example: 12345
        name:
          type: 'string'
          example: 'a name'
    commonLookupValueDetail:
      type: 'object'
      properties:
        type:
          type: 'string'
        code:
          type: 'string'
        description:
          type: 'string'
        start_date_active:
          type: 'string'
        attribute11:
          type: 'string'
        attribute12:
          type: 'string'
        enabled:
          type: 'boolean'
        default_code:
          type: 'string'
    commonLookupDetail:
      allOf:
        - $ref: "#/components/schemas/page"
      type: 'object'
      properties:
        content:
          type: 'array'
          items:
            $ref: "#/components/schemas/commonLookupValueDetail"
    page:
      type: 'object'
      properties:
        total_pages:
          type: 'integer'
        total_elements:
          type: 'integer'
        number:
          type: 'integer'
        size:
          type: 'integer'

