# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI caab-data-api pr to main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read
  packages: write

jobs:
    build-test-release:
      if: |
        github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'dependabot/')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            ref: main
            token: ${{ secrets.REPO_TOKEN }}
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Gradle
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: build

        - name: Test
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: jacocoTestCoverageVerification

        - name: Integration Test
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: integrationTest

        - name: Set to github user
          run: |
            git config --global user.email "github@justice.gov.uk"
            git config --global user.name "GitHub Actions Bot"

        - name: Update version
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: release -Prelease.useAutomaticVersion=true

